Added failing test for issue #87
RonnyPfannschmidt/prance pull request #90
Opened 2021-02-13 17:21 UTC by Goldziher

This PR adds the Kubernetes Swagger API specs and a rudimentary test that is failing. 

@jfinkhaeuser

2021-04-01 07:57 UTC, RonnyPfannschmidt requested changes

2021-04-01 17:29 UTC, Goldziher commented on tests/test_util_resolver.py
> +def test_issue_205_swagger_resolution_failure():
Sorry, can you explain what you mean?

2021-04-01 18:15 UTC, RonnyPfannschmidt commented on tests/test_util_resolver.py
> +def test_issue_205_swagger_resolution_failure():
mark it with xfail, and put the url to the issue into the reason

2021-04-09 14:49 UTC, Goldziher commented on tests/test_util_resolver.py
> +def test_issue_205_swagger_resolution_failure():
done @RonnyPfannschmidt

2021-04-09 14:50 UTC, Goldziher commented
Seems I need to rebase this on master

2021-04-09 14:52 UTC, RonnyPfannschmidt commented
i can just merge as is if its ok with you ^^

2021-04-09 14:54 UTC, Goldziher commented
Go ahead @RonnyPfannschmidt  - all is done.

2021-04-09 14:55 UTC, merged

2021-04-09 14:56 UTC, RonnyPfannschmidt commented
thanks :+1: